# Generated by Django 6.0 on 2025-12-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_gender', models.CharField(max_length=50)),
                ('employee_contact', models.CharField(max_length=50)),
                ('employee_doj', models.CharField(max_length=50)),
                ('employee_salary', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_designation')),
            ],
        ),
    ]
