# Generated by Django 6.0 on 2026-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
