# Generated by Django 6.0 on 2026-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
    ]
