# Generated by Django 6.0 on 2026-01-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_model',
        ),
    ]
