# Generated by Django 6.0 on 2026-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_breakdown_servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype_name', models.CharField(max_length=100)),
            ],
        ),
    ]
