# Generated by Django 6.0 on 2026-02-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_breakdown_servicetype'),
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_commision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.IntegerField(choices=[(1, 'Service Booking'), (2, 'Breakdown Assistance')])),
                ('booking_id', models.IntegerField()),
                ('admin_commision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
            ],
        ),
    ]
