# Generated by Django 6.0 on 2026-02-11 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_commision'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_commision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
