# Generated by Django 6.0 on 2026-01-14 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0017_tbl_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workedescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workedesc_content', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
            ],
        ),
    ]
