# Generated by Django 6.0 on 2026-01-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('technician_email', models.CharField(max_length=50)),
                ('technician_contact', models.CharField(max_length=50)),
                ('technician_photo', models.FileField(upload_to='Assets/TechnicianDocs/')),
                ('technician_password', models.CharField(max_length=50)),
            ],
        ),
    ]
