# Generated by Django 6.0 on 2026-01-07 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_servicetype'),
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('ServiceCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicecenterservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
            ],
        ),
    ]
