# Generated by Django 6.0 on 2026-01-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0002_tbl_servicecenterservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_technician',
        ),
    ]
