# Generated by Django 6.0 on 2026-01-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('ServiceCenter', '0003_delete_tbl_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('technician_email', models.CharField(max_length=50)),
                ('technician_contact', models.CharField(max_length=50)),
                ('technician_photo', models.FileField(upload_to='Assets/TechnicianDocs/')),
                ('technician_password', models.CharField(max_length=50)),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
            ],
        ),
    ]
