# Generated by Django 6.0 on 2026-02-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0004_tbl_technician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_servicecenterservices',
        ),
    ]
