# Generated by Django 6.0 on 2026-02-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_model'),
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('ServiceCenter', '0005_delete_tbl_servicecenterservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicecenterservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
            ],
        ),
    ]
