# Generated by Django 6.0 on 2026-01-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_subcategory'),
        ('Guest', '0004_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicecenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecenter_name', models.CharField(max_length=50)),
                ('servicecenter_email', models.CharField(max_length=50)),
                ('servicecenter_contact', models.CharField(max_length=50)),
                ('servicecenter_address', models.CharField(max_length=50)),
                ('servicecenter_logo', models.FileField(upload_to='Assets/ServicecenterDocs/')),
                ('servicecenter_license', models.FileField(upload_to='Assets/ServicecenterDocs/')),
                ('servicecenter_password', models.CharField(max_length=50)),
                ('servicecenter_status', models.IntegerField(default=0)),
                ('servicecenter_regdate', models.DateField(auto_now_add=True)),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
