# Generated by Django 6.0 on 2026-01-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_servicecenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_servicecenter',
            old_name='placeid',
            new_name='place',
        ),
    ]
