# Generated by Django 6.0 on 2026-01-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_servicetype'),
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_todate', models.DateField()),
                ('booking_amount', models.CharField(null=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_complaints', models.CharField(max_length=50)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
