# Generated by Django 6.0 on 2026-01-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_model'),
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('User', '0004_delete_tbl_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_year', models.CharField(max_length=50)),
                ('vehicle_photo', models.FileField(upload_to='Assets/VehicleDocs/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
