# Generated by Django 6.0 on 2026-01-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
