# Generated by Django 6.0 on 2026-01-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('ServiceCenter', '0004_tbl_technician'),
        ('User', '0017_tbl_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_breakdownassist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_date', models.DateField(auto_now_add=True)),
                ('breakdown_complaint', models.CharField(max_length=50)),
                ('breakdown_status', models.IntegerField(default=0)),
                ('breakdown_amount', models.CharField(null=True)),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecenter')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.tbl_technician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_vehicle')),
            ],
        ),
    ]
