# Generated by Django 6.0 on 2026-02-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_tbl_breakdownassist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_amount',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='service_type',
        ),
    ]
