# Generated by Django 6.0 on 2026-02-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0006_tbl_servicecenterservices'),
        ('User', '0019_remove_tbl_booking_booking_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('parts_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('servicecenter_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.tbl_servicecenterservices')),
            ],
        ),
    ]
