# Generated by Django 6.0 on 2026-02-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_booking_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_breakdownassist',
        ),
    ]
