# Generated by Django 6.0 on 2026-02-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0007_tbl_servicecenter_breakdown_services'),
        ('User', '0022_tbl_breakdownassist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_breakdown_booking_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_breakdownassist')),
                ('servicecenter_breakdown_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.tbl_servicecenter_breakdown_services')),
            ],
        ),
    ]
