# Generated by Django 6.0 on 2026-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_breakdown_booking_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_breakdown_booking_services',
            name='service_status',
            field=models.IntegerField(default=0),
        ),
    ]
