# Generated by Django 6.0 on 2026-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_breakdown_booking_services_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_breakdown_booking_services',
            name='service_status',
        ),
        migrations.AddField(
            model_name='tbl_breakdown_booking_services',
            name='progress_step',
            field=models.IntegerField(default=0),
        ),
    ]
