# Generated by Django 6.0 on 2026-02-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_remove_tbl_breakdown_booking_services_service_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_breakdown_booking_services',
        ),
    ]
