# Generated by Django 6.0 on 2026-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_tbl_breakdown_booking_services_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_breakdown_booking_services',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
