# Generated by Django 6.0 on 2026-02-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_placeid_tbl_servicecenter_place'),
        ('User', '0029_tbl_breakdown_booking_services_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='User.tbl_booking')),
                ('servicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Guest.tbl_servicecenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Guest.tbl_user')),
            ],
        ),
    ]
